language: go
go:
  - 1.16.x

jobs:
  include:
    - os: linux
      dist: xenial
      script:
        # golangci-lint is required by test.sh. Latest version here if you want
        # to bump it, version number is at the end of the "curl | sh"
        # commandline below:
        # https://github.com/golangci/golangci-lint/releases/latest
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.0

        - ./test.sh

    - os: windows
      script:
        - go build
        - go test -timeout 30s ./...
