name: Linux CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Install golangci-lint
        # golangci-lint is required by test.sh. Latest version here if you want
        # to bump it, version number is at the end of the "curl | sh"
        # commandline below:
        # https://github.com/golangci/golangci-lint/releases/latest
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)"/bin v1.50.1
      - run: ./test.sh
