name: Windows CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Add some caching, should help for PRs with multiple pushes.
      - uses: actions/setup-go@v3
        with:
          cache: true

      - run: go build
      - run: go test -timeout 30s ./...
